stac-utils/titiler-pgstac

tests/test_titiler_pgstac.py, titiler/pgstac/mosaic.py
ref https://github.com/stac-utils/pgstac/pull/52
=> Patch point seach

CHANGES.md, tests/test_titiler_pgstac.py, titiler/pgstac/factory.py, titiler/pgstac/mosaic.py
=> surface pgstac options in Tile endpoints

CHANGES.md, tests/test_titiler_pgstac.py, titiler/pgstac/mosaic.py
=> forward TMS to the reader

titiler/pgstac/factory.py
Rationale: https://github.com/stac-utils/titiler-pgstac/discussions/33
=> Add search_dependency

docs/advanced.md, mkdocs.yml
Added an example of using `search_dependency`.
=> Add 'Advanced Usage' section to the docs

titiler/pgstac/factory.py, titiler/pgstac/model.py
=> add pgstac Search model

CHANGES.md, setup.py, titiler/pgstac/dependencies.py, titiler/pgstac/factory.py, titiler/pgstac/version.py
=> update titiler requirement

tests/test_health.py, titiler/pgstac/main.py
According to the docs: https://www.psycopg.org/psycopg3/docs/advanced/async.html#disconnections
=> Database health check

docker-compose.yml, setup.py, tests/conftest.py
=> update tests for pgstac 0.6

CHANGES.md, tests/test_mosaic.py, titiler/pgstac/factory.py
This is a `big` breaking change but I believe it aligns more with usual OGC tiles specification 
cc @mmcfarland @lossyrob
=> Change Tile URL param order

.pre-commit-config.yaml, CHANGES.md, setup.py
ref https://github.com/developmentseed/titiler/issues/606
=> set maximum version of fastapi/starlette

docs/src/notebooks/demo.ipynb
Add missing dependencies for the demo notebook
Remove an extra whitespace
=> Add required dependencies for demo notebook

CHANGES.md, pyproject.toml, titiler/pgstac/model.py
=> remove stac-pydantic

CHANGES.md, tests/test_mosaic.py, titiler/pgstac/factory.py, titiler/pgstac/main.py
closes #114
This PR adds `tilejson` links in `/mosaic/register` and `/mosaic/{mosaic_id}/info` responses created from the `defaults` layer metadata.
```python
import httpx
import json
search = {
"filter-lang": "cql2-json",
"filter": {
"op": "=",
"args": [{"property": "collection"}, "world"],
},
"metadata": {
"defaults": {
"one_band": {
"assets": "cog",
"bidx": 1,
"rescale": "0,255",
},
"three_band": {
"assets": "cog",
"bidx": (1, 2, 3),
"rescale": "0,255",
},
}
}
}
resp = httpx.post("http://127.0.0.1:8081/mosaic/register", json=search)
print(json.dumps(resp.json()["links"], indent=4))
[
{
"rel": "metadata",
"title": "Mosaic metadata",
"type": "application/json",
"href": "http://127.0.0.1:8081/mosaic/66dacae5cf1e4278487e7d10daf6db15/info"
},
{
"rel": "tilejson",
"title": "Link for …
```
=> add tilejson links for layers

CHANGES.md, tests/test_mosaic.py, titiler/pgstac/factory.py
same as https://github.com/developmentseed/titiler/pull/726
=> enable algorithm in statistics endpoints

titiler/pgstac/factory.py
=> use the cellSize parameter instead of the _resolution method for the /map endpoint

tests/test_collections.py, tests/test_searches.py, titiler/pgstac/factory.py
ref https://github.com/stac-utils/titiler-pgstac/pull/150#issuecomment-1884665394
cc @hrodmn
=> rename point endpoint to with `/point` prefix

CHANGES.md, docker-compose.yml, pyproject.toml, tests/test_collections.py, tests/test_items.py, tests/test_searches.py, titiler/pgstac/extensions.py, titiler/pgstac/factory.py, titiler/pgstac/main.py, titiler/pgstac/model.py
same as https://github.com/developmentseed/titiler/pull/802
=> Deprecate default tilematrixset

CHANGES.md, docker-compose.yml, pyproject.toml, titiler/pgstac/model.py, titiler/pgstac/mosaic.py
=> update search model for pgstac 0.9

CHANGES.md, tests/conftest.py, tests/test_items.py, tests/test_readonly.py, titiler/pgstac/dependencies.py, titiler/pgstac/errors.py, titiler/pgstac/factory.py, titiler/pgstac/main.py
=> add check for read-only pgstac database

CHANGES.md, docs/src/endpoints/collections_endpoints.md, tests/conftest.py, tests/test_collections.py, tests/test_searches.py, titiler/pgstac/dependencies.py, titiler/pgstac/model.py
closes #220 
Q: should we add `filter`? 
Does pgstac only support `cql2-json` and `cql-json` @bitner ? if yes it means that we would have to add `pygeofilter` dependency 🙅 https://github.com/stac-utils/stac-fastapi-pgstac/blob/main/stac_fastapi/pgstac/core.py#L557-L560
=> add query and sortby

CHANGES.md, pyproject.toml, titiler/pgstac/backend.py, titiler/pgstac/factory.py, titiler/pgstac/main.py, titiler/pgstac/settings.py
This adds a few logging statements to add more context for request monitoring and adds an option to enable OpenTelemetry instrumentation.
Waiting for https://github.com/developmentseed/titiler/pull/1171 to be merged/released
=> [WIP] feat: add additional logging and telemetry option in application
