stac-utils/titiler-pgstac

README.md
setup.py
tox.ini

remove psycopg2 dependencies

---

CHANGES.md
README.md
docker-compose.yml
docs/endpoints.md
docs/intro.md
docs/notebooks/demo.ipynb
setup.py
tests/test_titiler_pgstac.py
titiler/pgstac/factory.py
titiler/pgstac/models.py
titiler/pgstac/mosaic.py

This PR Does:
- up titiler requirement to `0.4.0` 
Note: new titiler version changed a lot of `query-parameter` style and name see: https://github.com/developmentseed/titiler/discussions/396
For now the Tests fails because there has been a change in pgstac behaviour. When we register a Search request with a bbox we were expecting that requesting a tile outside the bbox would return empty items ... but it's no more the case with `0.4.0` 🤷‍♂️  cc @bitner

update for titiler 0.4.0

---

CHANGES.md
tests/test_titiler_pgstac.py
titiler/pgstac/factory.py
titiler/pgstac/models.py

closes #22 
This PR do:
- add `metadata` in Search model which will then be forwarded to the PgSTAC `search_query` function

add metadata in search model

---

.github/workflows/ci.yml
CHANGES.md
docs/endpoints.md
setup.py
tests/conftest.py
tests/test_titiler_pgstac.py
titiler/pgstac/factory.py

ref https://github.com/developmentseed/titiler/pull/430

add tilebuffer

---

tests/test_titiler_pgstac.py
titiler/pgstac/factory.py
titiler/pgstac/models.py

ref #30 
This PR adds a `SearchMetadata` model defining the `mosaic` metadata that could be provided by the user when `registering` a search request. 
```js
{
// OPTIONAL. Default: "mosaic" (No other value accepted for now). Describe the `type` of metadata. 
"type": "mosaic",
// OPTIONAL. Default: null.
// The maximum extent of available map tiles. The bounds are represented in WGS:84
// latitude and longitude values, in the order left, bottom, right, top.
// Values may be integers or floating point numbers.
"bounds": [ -180, -85.05112877980659, 180, 85.0511287798066 ],
// OPTIONAL. Default: null.
// An integer specifying the minimum zoom level.
"minzoom": 0,
// OPTIONAL. Default: null.
// An integer specifying the maximum zoom level. MUST be >= minzoom.
"maxzoom": 11,
// OPTIONAL. …
```

add metadata model

---

CHANGES.md
README.md
tests/test_items.py
tests/test_mosaic.py
titiler/pgstac/dependencies.py
titiler/pgstac/factory.py
titiler/pgstac/main.py
titiler/pgstac/reader.py

This PR adds a set of endpoints for single STAC items with `/stac` prefix. Item must be designed with `?item={item id}&collection={collection id}` query parameter. 
ref: https://github.com/microsoft/planetary-computer-apis/pull/55
**breaking change** 
* add `/mosaic` prefix to PgSTAC mosaic endpoints
cc @mmcfarland @lossyrob @moradology

add single item STAC endpoints

---

tests/test_mosaic.py
titiler/pgstac/factory.py
titiler/pgstac/main.py
titiler/pgstac/mosaic.py

this PR adds:
- a `feature()` method to the MosaicBackend 
- a `/statistics` (zonal stats) endpoints using ☝️

add optional statistics endpoint

---

CHANGES.md
tests/test_mosaic.py
titiler/pgstac/factory.py

This PR does:
Forward mosaic metadata name, zooms and bounds to the tilejson document

Insert mosaic metadata `min/max zoom` and `bounds` in tilejson

---

CHANGES.md
tests/conftest.py
titiler/pgstac/db.py
titiler/pgstac/main.py

Currently, this codebase expects that the postgres configuration be available via environment variables.  However, there are situations in which a user might not have these configurations available in the runtime environment.  For example, a user might want their application to be responsive to DB credential changes without redeployment so they fetch credentials at Lambda startup from AWS Secrets Manager.
This PR reworks the `connect_to_db()` to take the `PostgresSettings` instance as an argument (ie Inversion of Control).  This makes it easier for systems that depend on extending this codebase to customize how they generate settings.
/cc @anayeaye

Support providing postgres settings via argument

---

CHANGES.md
titiler/pgstac/settings.py

Using the LRU cache does not offer any benefit, as the settings are initialized just once at app startup:
https://github.com/stac-utils/titiler-pgstac/blob/780f4f8815f9349f72bb7805fad1306bb4412291/titiler/pgstac/main.py#L31
https://github.com/stac-utils/titiler-pgstac/blob/780f4f8815f9349f72bb7805fad1306bb4412291/titiler/pgstac/db.py#L12-L17
https://github.com/stac-utils/titiler-pgstac/blob/780f4f8815f9349f72bb7805fad1306bb4412291/titiler/pgstac/dependencies.py#L20
They additionally don't allow settings to be provided manually by keyword arguments.  If it is deemed preferable to have the LRU present, an alternative solution would be to alter the cached function to pass through kwargs to the settings class.

Remove LRU cache

---

.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGES.md
setup.py

ref https://github.com/developmentseed/titiler/issues/606

Fix for new starlette

---

CHANGES.md
docker-compose.yml
titiler/pgstac/db.py
titiler/pgstac/dependencies.py
titiler/pgstac/logger.py
titiler/pgstac/mosaic.py
titiler/pgstac/settings.py
titiler/pgstac/utils.py

This PR adds a `retry` mechanism to avoid error due to connection issue. 
The main idea is to use the `retry` decorator on top of the `execute_query` which is responsible for acquiring the connection within the `pool` and execute the SQL query. 
By default the `execute_query` will be retried only on [`psycopg.OperationalError`](https://www.psycopg.org/psycopg3/docs/api/errors.html#psycopg.OperationalError)
I've used `execute_query` only on the Mosaic backend `PGSTACBackend.get_assets` method which is called on each tile request. We could use it on all other endpoints but they are more easily retried manually 🤷 
cc @bitner @lossyrob @mmcfarland

add retry mechanism

---

CHANGES.md
pyproject.toml
tests/test_mosaic.py
titiler/pgstac/factory.py
titiler/pgstac/mosaic.py

closes #92 
* remove deprecated `/tiles/{searchid}/...` endpoints (replaced with `/{searchid}/tiles/...`)
* depreciate `/{searchid}/{z}/{x}/{y}/assets` endpoints and add `/{searchid}/tiles/{z}/{x}/{y}/assets`
* update minimum titiler requirement to `>=0.11.6`
* remove timing headers
* add `strict_zoom` option (controled with `MOSAIC_STRICT_ZOOM` environment variable) to raise (or not) error when fetching tile outside mosaic min/max zoom range

update titiler version and remove timings

---

CHANGES.md
titiler/pgstac/main.py
titiler/pgstac/settings.py

FYI @ivica3730k I've added `root_path` settings (which was missing), it might not fix the issue but I know root_path was previously mentioned in titiler repo when using proxy (https://github.com/developmentseed/titiler/pull/343)
closes #110

change openapi/docs url and update landing page

---

CHANGES.md
docs/src/advanced/custom_search.md
docs/src/tiler_factories.md
titiler/pgstac/main.py

https://fastapi.tiangolo.com/advanced/events/?h=lifesp#alternative-events-deprecated

FastAPI lifespan

---

.github/workflows/ci.yml
CHANGES.md
docs/src/intro.md
docs/src/mosaic_endpoints.md
pyproject.toml
tests/test_mosaic.py
titiler/pgstac/factory.py
titiler/pgstac/templates/wmts.xml

Similar as #120 but within the wmts endpoints
~~This is blocked for now because~~:
- ~~This remove any query-parameter check (assets) in the endpoint~~
- ~~Testing locally (in QGIS) didn't work, for some reason it request URL with a weird encoding~~
cc @geospatial-jeff 
~~Note: This will be quite a breaking change for the wmts endpoint so It's not 💯 sure that it will get merged, but maybe added as an extension or an example in the documentation~~

Support multiple Layers in WMTS endpoint

---

CHANGES.md
docs/src/advanced/custom_search.md
docs/src/advanced/metadata.md
docs/src/intro.md
docs/src/mosaic_endpoints.md
docs/src/tiler_factories.md
titiler/pgstac/extensions.py
titiler/pgstac/factory.py
titiler/pgstac/main.py

This PR moves `/{search_id}/info` endpoint outside the `MosaicTilerFactory` to its own *extension* (`titiler.pgstac.extension.searchInfoExtension`)

add searchInfoExtension

---

.github/workflows/tests/benchmarks.py
.github/workflows/tests/conftest.py
CHANGES.md
tests/test_mosaic.py
titiler/pgstac/extensions.py
titiler/pgstac/factory.py
titiler/pgstac/main.py

second take at #127 
Goal of this PR is to allow custom prefixed for PgSTAC Mosaics  such as `/collections/{collection_id}` (In addition of `/mosaic/{search_id}` 
- `/mosaic/{search_id}` -> `/mosaics/{search_id}` 
- add `layers` in `/mosaics/{search_id}/info` response (for Map and TileJSON links)
- Moves `/list` and `/register` endpoint creation to their own utility function (`add_mosaic_register_route` and `add_mosaic_list_route` 
```python
add_register_route(
app,
prefix="/mosaics",
tile_dependencies=[
mosaic.layer_dependency,
mosaic.dataset_dependency,
mosaic.pixel_selection_dependency,
mosaic.process_dependency,
mosaic.rescale_dependency,
mosaic.colormap_dependency,
mosaic.render_dependency,
mosaic.pgstac_dependency,
mosaic.reader_dependency,
mosaic.backend_dependency,
], …
```

refactor factories to allow more custom prefixes

---

.github/workflows/tests/benchmarks.py
.github/workflows/tests/conftest.py
CHANGES.md
tests/test_collections.py
tests/test_searches.py
titiler/pgstac/dependencies.py
titiler/pgstac/factory.py
titiler/pgstac/main.py

ref #118 
This PR uses the latest changes in titiler-pgstac to add `/collection/{collection_id}` endpoints 
- update endpoints Tags 
- add `py.typed` file 
- move mosaic endpoints from `/mosaics/{search_id}` to `/searches/{search_id}`

add /collections/{collection_id} endpoints

---

tests/test_collections.py
tests/test_searches.py
titiler/pgstac/factory.py
titiler/pgstac/model.py
titiler/pgstac/mosaic.py

I added the capability to query asset values at a point as discussed in https://github.com/stac-utils/titiler-pgstac/discussions/144.
Rather than a dedicated `/point` endpoint, I followed the pattern for querying assets at a lon/lat pair (`{lon}/{lat}/assets`).
I tried to mimic the response class from the analagous titiler endpoint, the only difference is that the `assets` object comes back as a list. It looks like this:
```
{
'coordinates': [-85.5, 36.1624],
'values': [
[
['https://noaa-eri-pds.s3.us-east-1.amazonaws.com/2020_Nashville_Tornado/20200307a_RGB/20200307aC0853130w361030n.tif'],
[27.0, 34.0, 42.0],
['cog_b1', 'cog_b2', 'cog_b3']
],
[
['https://noaa-eri-pds.s3.us-east-1.amazonaws.com/2020_Nashville_Tornado/20200307a_RGB/20200307aC0853000w361030n.tif'],
[30.0, 34.0, 43.0], …
```

add /{lon},{lat}/values endpoints

---

CHANGES.md
pyproject.toml
titiler/pgstac/factory.py
titiler/pgstac/main.py

* update rio-tiler version to `>6.3.0` (defined in `titiler>=0.17`)
* use new `align_bounds_with_dataset=True` rio-tiler option in GeoJSON statistics methods for more precise calculation [backported from 1.2.0]
* use morecantile `TileMatrixSet.cellSize` property instead of deprecated/private TileMatrixSet._resolution method [backported from 1.1.0]

update rio-tiler, add align stats and fix morecantile breaking change

---

titiler/pgstac/db.py

RDS Proxy does not support command line options and therefore titiler cannot connect to the proxy using the`search_path` option. Make the `ConnectionPool` kwargs optional.

Change db connection kwargs default

---

docs/src/intro.md

Link was broken due to file rename:
https://github.com/stac-utils/titiler-pgstac/commits/694e18552f0090d68fcb3d05d914ca32b70db6d4/docs/src/items_endpoints.md?browsing_rename_history=true&new_path=docs/src/endpoints/items_endpoints.md&original_branch=main

Update Items endpoints link

---

CONTRIBUTING.md

Adds the `psycopg` extra to the "dev install" `pip install` command.
Also changes `cd titiler` to `cd titiler-pgstac` to move into the `titiler-pgstac` repo (probably leftover copypasta from `titiler` repo 😄)
Closes #166

Fix dev install instructions so tests will run

---

CHANGES.md
tests/conftest.py
tests/test_searches.py
titiler/pgstac/main.py
titiler/pgstac/settings.py

closes #174 
@drnextgis do you see other paths that should be excluded by default?

add cachecontrol_exclude_paths in ApiSettings

---

pyproject.toml
tests/conftest.py
titiler/pgstac/settings.py

This PR does:
- switch to `pytest-postgresql` from `pytest-psql` which is no more maintained
- use quote-plus to encode postgres password https://github.com/stac-utils/stac-fastapi-pgstac/pull/122

switch to pytest-postgresql

---

CHANGES.md
docker-compose.yml
docs/src/endpoints/collections_endpoints.md
tests/test_collections.py
tests/test_searches.py
titiler/pgstac/dependencies.py

add ids, bbox and datetime parameters to the collections endpoints

---

.github/workflows/deploy_mkdocs.yml
docs/mkdocs.yml
docs/src/api/titiler/pgstac/db.md
docs/src/api/titiler/pgstac/dependencies.md
docs/src/api/titiler/pgstac/extensions.md
docs/src/api/titiler/pgstac/factory.md
docs/src/api/titiler/pgstac/model.md
docs/src/api/titiler/pgstac/mosaic.md
docs/src/api/titiler/pgstac/reader.md
docs/src/api/titiler/pgstac/settings.md
docs/src/api/titiler/pgstac/utils.md
pyproject.toml

switch to mkdocstrings

---

docs/src/intro.md

Just removing the extra set of parentheses that erroneously link to https://stac-utils.github.io/titiler-pgstac/latest/intro/(https://github.com/radiantearth/stac-api-spec/tree/master/item-search)

Fix broken link in intro.md

---

CHANGES.md
pyproject.toml
tests/test_readonly.py
titiler/pgstac/extensions.py
titiler/pgstac/factory.py
titiler/pgstac/main.py
titiler/pgstac/templates/index.html

https://github.com/developmentseed/titiler/blob/main/CHANGES.md#0200-2025-01-07
* remove `rescale_dependency` and `color_formula_dependency` attributes in `TilerFactory` class  **breaking change**
* add `render_func: Callable[..., Tuple[bytes, str]] = render_image` attribute in `TilerFactory` class
* update `/healthz` endpoint to return dependencies versions (titiler, rasterio, gdal, ...)
* migrate `templates/index.html` to bootstrap5, remove unused css, reuse bs classes
* Updated WMTS endpoint to return layer bounds in coordinate ordering matching CRS order if WGS84 is not used

update from titiler 0.20

---

CHANGES.md
docker-compose.yml
nginx.conf
titiler/pgstac/main.py

fix links when app is behind proxy
